name: CI
on:
  push:
    branches: [ main ]

jobs:
  TEST-Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
         python -m pip install -r .github/workflows/requirements.txt

    - name: Run Tests
      run: |
        robot Test/

    - name: If Auto Test Pass Rate Not 100%, Job Will Fail
      if: env.ROBOT_RC != '0'
      run: |
        echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
        exit 1
